#setwd("/home/shailja/courses/exploratory data analysis/ExData_Plotting1")
data <- read.table("./Data/household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
subset <- data[data$Date %in% c("1/2/2007","2/2/2007") ,]
png("plot3.png", width=480, height=480)
subset$DateTime <- strptime(paste(subset$Date, subset$Time), "%d/%m/%Y %H:%M:%S")
plot(subset$DateTime,subset$Sub_metering_1,type="l",col="black",xlab="",ylab="Energy Submetering")
lines(subset$DateTime,subset$Sub_metering_2,type="l",col="red")
lines(subset$DateTime,subset$Sub_metering_3,type="l",col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,lwd=2.5,col=c("black","red","blue"))
dev.off()